### ISSUE TITLE
BadResponse Error when trying to login

### ISSUE THREAD

**Issue by DestinyofYeet** [George-Miao/qbit#12]
Hi,

calling 
```rust
client.login(true).await.unwrap();
```

fails with a 

```called `Result::unwrap()` on an `Err` value: BadResponse { explain: "Failed to extract cookie from response" }```

error.

This happens when trying to use credentials. When setting the WebUI to bypass authentication it doesn't come up
[log.txt](https://github.com/George-Miao/qbit/files/14816542/log.txt)

Qbittorrent version: 4.6.4
Qbit-rs: 0.4.1

**Comment by George-Miao** [comment]
Did you try to manually request the API and see if the cookie header is being set? Also, please provide more information on how you produce the error, and please make sure your credential is valid.

**Comment by DestinyofYeet** [comment]
Hey, took a look at my project again and realized that the error was due to my credentials not being parsed correctly => They were invalid.
