### ISSUE TITLE
extra quotes appeared in category when adding a torrent

### ISSUE THREAD

**Issue by shenjiangqiu** [George-Miao/qbit#24]
when adding a torrent, there are extra quotes around the catogory name:
![Screenshot_20241110_100937](https://github.com/user-attachments/assets/9a4a1777-e9d6-4a6c-ad67-b60ba7f84ca0)

**Comment by shenjiangqiu** [comment]
fix it in #23

**Comment by George-Miao** [comment]
Fixed in #23
